version: '3.7'

volumes:
  mysql_data:

services:
  db:
    container_name: sqs_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s  # Verkürzte Intervallzeit
      timeout: 5s  # Verkürzte Timeoutzeit
      retries: 3  # Weniger Wiederholungen
      start_period: 10s  # Kürzere Startperiode

  backend:
    restart: unless-stopped
    container_name: sqs_backend
    image: ghcr.io/lmaistud/sqs-projekt/sqs_backend:latest
    environment:
      - DB_HOST=db
      - JAVA_DEBUG=true
      - JAVA_DEBUG_PORT=5005
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    restart: unless-stopped
    container_name: sqs_frontend
    image: ghcr.io/lmaistud/sqs-projekt/sqs_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      
